<?xml version="1.0" encoding="utf-8"?>
<sdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
  <head>
    <schema href="sdata_schema.xml"/>
    <references>
      <reffile id="t" name="tdata" href="ln94203_3.t.gz"/>
      <reffile id="s" name="semlex" href="semlex.xml"/>
    </references>
  </head>
  <meta>
    <annotation_info>
      <lexicon>SemLex Devel</lexicon>
      <annotator>vimmrova</annotator>
      <version_info/>
      <desc/>
    </annotation_info>
  </meta>
  <wsd>
    <st id="s-ln94203-3-l2" src="auto">
      <lexicon-id>s##person</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p4s2w12</LM>
        <LM>t#t-ln94203-3-p4s2w13</LM>
      </tnode.rfs>
    </st>
    <st id="s-ln94203-3-l3">
      <lexicon-id>s##institution</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p4s2w15</LM>
        <LM>t#t-ln94203-3-p4s2w17</LM>
        <LM>t#t-ln94203-3-p4s2w18</LM>
        <LM>t#t-ln94203-3-p4s2w19</LM>
        <LM>t#t-ln94203-3-p4s2w20</LM>
        <LM>t#t-ln94203-3-p4s2w21</LM>
      </tnode.rfs>
    </st>
    <st id="s-ln94203-3-l4">
      <lexicon-id>s##location</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p5s1w7</LM>
        <LM>t#t-ln94203-3-p5s1w8</LM>
      </tnode.rfs>
    </st>
    <st id="s-ln94203-3-l5">
      <lexicon-id>s##person</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p5s1w19</LM>
        <LM>t#t-ln94203-3-p5s1w21</LM>
      </tnode.rfs>
    </st>
    <st id="s-ln94203-3-l6">
      <lexicon-id>s##location</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p5s6w2</LM>
        <LM>t#t-ln94203-3-p5s6w3</LM>
      </tnode.rfs>
    </st>
    <st id="s-ln94203-3-l7">
      <lexicon-id>s#0000025022</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p2s1w17</LM>
        <LM>t#t-ln94203-3-p2s1w18</LM>
      </tnode.rfs>
    </st>
    <st id="s-ln94203-3-l8">
      <lexicon-id>s#0000010260</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p3s2w20</LM>
        <LM>t#t-ln94203-3-p3s2w21</LM>
        <LM>t#t-ln94203-3-p3s2w22</LM>
      </tnode.rfs>
    </st>
    <st id="s-ln94203-3-l9" src="auto">
      <lexicon-id>s#0000010260</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p4s3w7</LM>
        <LM>t#t-ln94203-3-p4s3w8</LM>
        <LM>t#t-ln94203-3-p4s3w9</LM>
      </tnode.rfs>
    </st>
    <st id="s-ln94203-3-l10" src="auto">
      <lexicon-id>s#0000010260</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p5s6w14</LM>
        <LM>t#t-ln94203-3-p5s6w15</LM>
        <LM>t#t-ln94203-3-p5s6w16</LM>
      </tnode.rfs>
    </st>
    <st id="s-ln94203-3-l11">
      <lexicon-id>s#0000031685</lexicon-id>
      <tnode.rfs>
        <LM>t#t-ln94203-3-p5s5w7</LM>
        <LM>t#t-ln94203-3-p5s5w8</LM>
        <LM>t#t-ln94203-3-p5s5w9</LM>
      </tnode.rfs>
    </st>
  </wsd>
</sdata>
