<?xml version="1.0" encoding="utf-8"?>
<sdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="sdata_schema.xml" />
  <references>
    <reffile id="t" name="tdata" href="mf930709_001.t.gz" />
    <reffile id="s" name="semlex" href="semlex.xml" />
  </references>
 </head>
 <meta>
  <annotation_info>
      <lexicon>SemLex Devel</lexicon>
      <annotator>named_entity_recogniser, stastna</annotator>
      <version_info></version_info>
      <desc></desc>
  </annotation_info>
 </meta>
 <wsd>
     <st id="s-mf930709-001-l6">
         <lexicon-id>s##time</lexicon-id>
         <t.rf>t#t-mf930709-001-p3s1Bw5</t.rf>
         <t.rf>t#t-mf930709-001-p3s1Bw7</t.rf>
     </st>
     <st id="s-mf930709-001-l13">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w12</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w13</t.rf>
     </st>
     <st id="s-mf930709-001-l18">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w22</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w23</t.rf>
     </st>
     <st id="s-mf930709-001-l23">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w32</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w33</t.rf>
     </st>
     <st id="s-mf930709-001-l29">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w45</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w46</t.rf>
     </st>
     <st id="s-mf930709-001-l32">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w53</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w54</t.rf>
     </st>
     <st id="s-mf930709-001-l35">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w56</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w57</t.rf>
     </st>
     <st id="s-mf930709-001-l38">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w59</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w60</t.rf>
     </st>
     <st id="s-mf930709-001-l43">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w63</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w64</t.rf>
     </st>
     <st id="s-mf930709-001-l46">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s2w5</t.rf>
         <t.rf>t#t-mf930709-001-p4s2w6</t.rf>
     </st>
     <st id="s-mf930709-001-l49">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s2w8</t.rf>
         <t.rf>t#t-mf930709-001-p4s2w9</t.rf>
     </st>
     <st id="s-mf930709-001-l52">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s2w11</t.rf>
         <t.rf>t#t-mf930709-001-p4s2w12</t.rf>
     </st>
     <st id="s-mf930709-001-l55">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s3w6</t.rf>
         <t.rf>t#t-mf930709-001-p4s3w7</t.rf>
     </st>
     <st id="s-mf930709-001-l58">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s4w5</t.rf>
         <t.rf>t#t-mf930709-001-p4s4w6</t.rf>
     </st>
     <st id="s-mf930709-001-l60">
         <lexicon-id>s##location</lexicon-id>
         <t.rf>t#t-mf930709-001-p3s1Bw9</t.rf>
         <t.rf>t#t-mf930709-001-p3s1Bw10</t.rf>
     </st>
     <st id="s-mf930709-001-l61">
         <lexicon-id>s##institution</lexicon-id>
         <t.rf>t#t-mf930709-001-p3s1Bw14</t.rf>
         <t.rf>t#t-mf930709-001-p3s1Bw15</t.rf>
     </st>
     <st id="s-mf930709-001-l62" src="auto">
         <lexicon-id>s##institution</lexicon-id>
         <t.rf>t#t-mf930709-001-p3s3w1</t.rf>
         <t.rf>t#t-mf930709-001-p3s3w2</t.rf>
     </st>
     <st id="s-mf930709-001-l64">
         <lexicon-id>s##other</lexicon-id>
         <t.rf>t#t-mf930709-001-p3s7w5</t.rf>
         <t.rf>t#t-mf930709-001-p3s7w6</t.rf>
     </st>
     <st id="s-mf930709-001-l66">
         <lexicon-id>s##institution</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w9</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w10</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w11</t.rf>
     </st>
     <st id="s-mf930709-001-l71">
         <lexicon-id>s##person</lexicon-id>
         <t.rf>t#t-mf930709-001-p4s1w42</t.rf>
         <t.rf>t#t-mf930709-001-p4s1w43</t.rf>
     </st>
 </wsd>
</sdata>