<?xml version="1.0" encoding="utf-8"?>

<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="tdata_schema.xml" />
  <references>
   <reffile id="a" name="adata" href="mf930709_001.a.gz" />
   <reffile id="v" name="vallex" href="vallex.xml" />
  </references>
 </head>
 <meta>
  <annotation_info>
   <desc>Manual annotation</desc>
  </annotation_info>
 </meta>
 <trees>
  <LM id="t-mf930709-001-p1s1">
   <atree.rf>a#a-mf930709-001-p1s1</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p1s1w5">
     <a>
      <lex.rf>a#a-mf930709-001-p1s1w5</lex.rf>
      <aux.rf>a#a-mf930709-001-p1s1w2</aux.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>jmenovat</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>3</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>hrt</deontmod>
      <tense>sim</tense>
      <aspect>cpl</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w1344f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p1s1w1">
       <a>
        <lex.rf>a#a-mf930709-001-p1s1w1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>prezident</t_lemma>
       <functor>ACT</functor>
       <tfa>c</tfa>
       <deepord>1</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>sg</number>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p1s1w4">
       <a>
        <lex.rf>a#a-mf930709-001-p1s1w4</lex.rf>
        <aux.rf>a#a-mf930709-001-p1s1w3</aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>týden</t_lemma>
       <functor>TWHEN</functor>
       <subfunctor>after</subfunctor>
       <tfa>t</tfa>
       <deepord>2</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p1s1w7">
       <a>
        <lex.rf>a#a-mf930709-001-p1s1w7</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>soudce</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>4</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>pl</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p1s1w6">
         <a>
          <lex.rf>a#a-mf930709-001-p1s1w6</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>ústavní</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>5</deepord>
         <gram>
          <sempos>adj.denot</sempos>
          <degcmp>pos</degcmp>
          <negation>neg0</negation>
         </gram>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p2s1">
   <atree.rf>a#a-mf930709-001-p2s1</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p2s1w2">
     <a>
      <lex.rf>a#a-mf930709-001-p2s1w2</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>doporučit</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>3</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>cpl</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w670f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p2s1w1">
       <a>
        <lex.rf>a#a-mf930709-001-p2s1w1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>parlament</t_lemma>
       <functor>ACT</functor>
       <tfa>c</tfa>
       <deepord>1</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p2s1a0">
       <nodetype>qcomplex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#Gen</t_lemma>
       <functor>ADDR</functor>
       <tfa>t</tfa>
       <deepord>2</deepord>
      </LM>
      <LM id="t-mf930709-001-p2s1w4">
       <a>
        <lex.rf>a#a-mf930709-001-p2s1w4</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>kandidát</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>4</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>pl</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p2s1w3">
         <a>
          <lex.rf>a#a-mf930709-001-p2s1w3</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>třináct</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>5</deepord>
         <gram>
          <sempos>adj.quant.def</sempos>
          <numertype>basic</numertype>
         </gram>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p3s1A">
   <atree.rf>a#a-mf930709-001-p3s1A</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p3s1Aw1">
     <a>
      <lex.rf>a#a-mf930709-001-p3s1Aw1</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>Praha</t_lemma>
     <functor>DENOM</functor>
     <tfa>f</tfa>
     <deepord>1</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>n.denot</sempos>
      <gender>fem</gender>
      <number>sg</number>
     </gram>
     <children>
      <LM id="t-mf930709-001-p3s1Aw4">
       <a>
        <lex.rf>a#a-mf930709-001-p3s1Aw4</lex.rf>
       </a>
       <nodetype>coap</nodetype>
       <t_lemma>#Comma</t_lemma>
       <functor>CONJ</functor>
       <is_parenthesis>1</is_parenthesis>
       <deepord>3</deepord>
       <sentmod>enunc</sentmod>
       <children>
        <LM id="t-mf930709-001-p3s1Aw3">
         <a>
          <lex.rf>a#a-mf930709-001-p3s1Aw3</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>li</t_lemma>
         <functor>PAR</functor>
         <is_member>1</is_member>
         <is_parenthesis>1</is_parenthesis>
         <tfa>f</tfa>
         <deepord>2</deepord>
         <is_name_of_person>1</is_name_of_person>
         <gram>
          <sempos>n.denot</sempos>
          <gender>nr</gender>
          <number>nr</number>
         </gram>
        </LM>
        <LM id="t-mf930709-001-p3s1Aw5">
         <a>
          <lex.rf>a#a-mf930709-001-p3s1Aw5</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>ben</t_lemma>
         <functor>PAR</functor>
         <is_member>1</is_member>
         <is_parenthesis>1</is_parenthesis>
         <tfa>f</tfa>
         <deepord>4</deepord>
         <is_name_of_person>1</is_name_of_person>
         <gram>
          <sempos>n.denot</sempos>
          <gender>nr</gender>
          <number>nr</number>
         </gram>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p3s1B">
    <mwes>
        <st id="s-mf930709-001-l6">
<<<<<<< HEAD:tred-integration/mf930709_001.t
        <lexicon-id>s##time</lexicon-id>
        <t.rf>
=======
            <lexicon-id>s##time</lexicon-id>
            <t.rf>
>>>>>>> 31ba0f1b54f286fb81467cb76ebbddb4fea00665:tred-integration/mf930709_001.t
                <LM>t-mf930709-001-p3s1Bw5</LM>
                <LM>t-mf930709-001-p3s1Bw7</LM>
            </t.rf>
        </st>
    </mwes>
   <atree.rf>a#a-mf930709-001-p3s1B</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p3s1Bw11">
     <a>
      <lex.rf>a#a-mf930709-001-p3s1Bw11</lex.rf>
      <aux.rf>
       <LM>a#a-mf930709-001-p3s1Bw3</LM>
       <LM>a#a-mf930709-001-p3s1Bw4</LM>
      </aux.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>jmenovat</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>7</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>cdn</verbmod>
      <deontmod>hrt</deontmod>
      <tense>sim</tense>
      <aspect>cpl</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w1344f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p3s1Bw2">
       <a>
        <lex.rf>a#a-mf930709-001-p3s1Bw2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>Havel</t_lemma>
       <functor>ACT</functor>
       <tfa>c</tfa>
       <deepord>1</deepord>
       <is_name_of_person>1</is_name_of_person>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s1Bw1">
         <a>
          <lex.rf>a#a-mf930709-001-p3s1Bw1</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>prezident</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>2</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>anim</gender>
          <number>sg</number>
         </gram>
        </LM>
       </children>
      </LM>
      <LM id="t-mf930709-001-p3s1Bw7">
       <a>
        <lex.rf>a#a-mf930709-001-p3s1Bw7</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>červenec</t_lemma>
       <functor>TWHEN</functor>
       <subfunctor>basic</subfunctor>
       <tfa>t</tfa>
       <deepord>3</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s1Bw5">
         <a>
          <lex.rf>a#a-mf930709-001-p3s1Bw5</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>15</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>4</deepord>
         <gram>
          <sempos>adj.quant.def</sempos>
          <numertype>ord</numertype>
         </gram>
        </LM>
       </children>
      </LM>
      <LM id="t-mf930709-001-p3s1Bw10">
       <a>
        <lex.rf>a#a-mf930709-001-p3s1Bw10</lex.rf>
        <aux.rf>a#a-mf930709-001-p3s1Bw8</aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>hrad</t_lemma>
       <functor>LOC</functor>
       <subfunctor>basic</subfunctor>
       <tfa>t</tfa>
       <deepord>5</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s1Bw9">
         <a>
          <lex.rf>a#a-mf930709-001-p3s1Bw9</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>Pražský</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>6</deepord>
         <gram>
          <sempos>adj.denot</sempos>
          <degcmp>pos</degcmp>
          <negation>neg0</negation>
         </gram>
        </LM>
       </children>
      </LM>
      <LM id="t-mf930709-001-p3s1Bw13">
       <a>
        <lex.rf>a#a-mf930709-001-p3s1Bw13</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>soudce</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>8</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>pl</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s1Bw15">
         <a>
          <lex.rf>a#a-mf930709-001-p3s1Bw15</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>soud</t_lemma>
         <functor>APP</functor>
         <tfa>f</tfa>
         <deepord>9</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>inan</gender>
          <number>sg</number>
         </gram>
         <children>
          <LM id="t-mf930709-001-p3s1Bw14">
           <a>
            <lex.rf>a#a-mf930709-001-p3s1Bw14</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>ústavní</t_lemma>
           <functor>RSTR</functor>
           <tfa>f</tfa>
           <deepord>10</deepord>
           <gram>
            <sempos>adj.denot</sempos>
            <degcmp>pos</degcmp>
            <negation>neg0</negation>
           </gram>
          </LM>
         </children>
        </LM>
        <LM id="t-mf930709-001-p3s1Bw12">
         <a>
          <lex.rf>a#a-mf930709-001-p3s1Bw12</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>třináct</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>11</deepord>
         <gram>
          <sempos>adj.quant.def</sempos>
          <numertype>basic</numertype>
         </gram>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p3s2">
   <atree.rf>a#a-mf930709-001-p3s2</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p3s2w1">
     <a>
      <lex.rf>a#a-mf930709-001-p3s2w1</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>říci</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>3</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>cpl</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w5874f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p3s2w3">
       <a>
        <lex.rf>a#a-mf930709-001-p3s2w3</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>ten</t_lemma>
       <functor>EFF</functor>
       <tfa>t</tfa>
       <deepord>1</deepord>
       <gram>
        <sempos>adj.pron.def.demon</sempos>
       </gram>
       <coref_text.rf>t-mf930709-001-p3s1Bw11</coref_text.rf>
      </LM>
      <LM id="t-mf930709-001-p3s2w2">
       <a>
        <lex.rf>a#a-mf930709-001-p3s2w2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>#PersPron</t_lemma>
       <functor>ADDR</functor>
       <tfa>t</tfa>
       <deepord>2</deepord>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>nr</gender>
        <number>pl</number>
        <person>1</person>
        <politeness>basic</politeness>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p3s2w4">
       <a>
        <lex.rf>a#a-mf930709-001-p3s2w4</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>včera</t_lemma>
       <functor>TWHEN</functor>
       <subfunctor>basic</subfunctor>
       <tfa>f</tfa>
       <deepord>4</deepord>
       <gram>
        <sempos>adv.denot.ngrad.nneg</sempos>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p3s2w6">
       <a>
        <lex.rf>a#a-mf930709-001-p3s2w6</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>mluvčí</t_lemma>
       <functor>ACT</functor>
       <tfa>f</tfa>
       <deepord>6</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s2w5">
         <a>
          <lex.rf>a#a-mf930709-001-p3s2w5</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>prezident</t_lemma>
         <functor>RSTR</functor>
         <tfa>t</tfa>
         <deepord>5</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>anim</gender>
          <number>sg</number>
         </gram>
        </LM>
       </children>
      </LM>
      <LM id="t-mf930709-001-p3s2w7">
       <a>
        <lex.rf>a#a-mf930709-001-p3s2w7</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>krátký</t_lemma>
       <functor>TWHEN</functor>
       <subfunctor>basic</subfunctor>
       <tfa>f</tfa>
       <deepord>7</deepord>
       <gram>
        <sempos>adj.denot</sempos>
        <degcmp>pos</degcmp>
        <negation>neg0</negation>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s2w12">
         <a>
          <lex.rf>a#a-mf930709-001-p3s2w12</lex.rf>
          <aux.rf>
           <LM>a#a-mf930709-001-p3s2w10</LM>
           <LM>a#a-mf930709-001-p3s2w8</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>vyslovit</t_lemma>
         <functor>TWHEN</functor>
         <subfunctor>after</subfunctor>
         <tfa>f</tfa>
         <deepord>9</deepord>
         <gram>
          <sempos>v</sempos>
          <verbmod>ind</verbmod>
          <deontmod>decl</deontmod>
          <tense>ant</tense>
          <aspect>cpl</aspect>
          <resultative>res0</resultative>
          <dispmod>disp0</dispmod>
          <iterativeness>it0</iterativeness>
         </gram>
         <val_frame.rf>v#v-w8359f1</val_frame.rf>
         <children>
          <LM id="t-mf930709-001-p3s2w11">
           <a>
            <lex.rf>a#a-mf930709-001-p3s2w11</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>parlament</t_lemma>
           <functor>ACT</functor>
           <tfa>c</tfa>
           <deepord>8</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>inan</gender>
            <number>sg</number>
           </gram>
          </LM>
          <LM id="t-mf930709-001-p3s2w13">
           <a>
            <lex.rf>a#a-mf930709-001-p3s2w13</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>souhlas</t_lemma>
           <functor>CPHR</functor>
           <tfa>f</tfa>
           <deepord>11</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>inan</gender>
            <number>sg</number>
           </gram>
           <val_frame.rf>v#v-w6273f1</val_frame.rf>
           <children>
            <LM id="t-mf930709-001-p3s2a1">
             <nodetype>qcomplex</nodetype>
             <is_generated>1</is_generated>
             <t_lemma>#QCor</t_lemma>
             <functor>ACT</functor>
             <tfa>t</tfa>
             <deepord>10</deepord>
             <coref_gram.rf>t-mf930709-001-p3s2w11</coref_gram.rf>
            </LM>
            <LM id="t-mf930709-001-p3s2w15">
             <a>
              <lex.rf>a#a-mf930709-001-p3s2w15</lex.rf>
              <aux.rf>a#a-mf930709-001-p3s2w14</aux.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>třináct</t_lemma>
             <functor>PAT</functor>
             <tfa>f</tfa>
             <deepord>12</deepord>
             <gram>
              <sempos>n.quant.def</sempos>
              <gender>nr</gender>
              <number>pl</number>
              <numertype>basic</numertype>
             </gram>
             <children>
              <LM id="t-mf930709-001-p3s2w18">
               <a>
                <lex.rf>a#a-mf930709-001-p3s2w18</lex.rf>
                <aux.rf>a#a-mf930709-001-p3s2w16</aux.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>kandidát</t_lemma>
               <functor>DIR1</functor>
               <subfunctor>basic</subfunctor>
               <tfa>f</tfa>
               <deepord>13</deepord>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>pl</number>
               </gram>
               <children>
                <LM id="t-mf930709-001-p3s2w17">
                 <a>
                  <lex.rf>a#a-mf930709-001-p3s2w17</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>čtrnáct</t_lemma>
                 <functor>RSTR</functor>
                 <tfa>f</tfa>
                 <deepord>14</deepord>
                 <gram>
                  <sempos>adj.quant.def</sempos>
                  <numertype>basic</numertype>
                 </gram>
                </LM>
                <LM id="t-mf930709-001-p3s2w20">
                 <a>
                  <lex.rf>a#a-mf930709-001-p3s2w20</lex.rf>
                  <aux.rf>a#a-mf930709-001-p3s2w19</aux.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>soudce</t_lemma>
                 <functor>PAT</functor>
                 <tfa>f</tfa>
                 <deepord>15</deepord>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>anim</gender>
                  <number>pl</number>
                 </gram>
                </LM>
                <LM id="t-mf930709-001-p3s2w24">
                 <a>
                  <lex.rf>a#a-mf930709-001-p3s2w24</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>navrhnout</t_lemma>
                 <functor>RSTR</functor>
                 <tfa>f</tfa>
                 <deepord>19</deepord>
                 <gram>
                  <sempos>v</sempos>
                  <verbmod>ind</verbmod>
                  <deontmod>decl</deontmod>
                  <tense>ant</tense>
                  <aspect>cpl</aspect>
                  <resultative>res0</resultative>
                  <dispmod>disp0</dispmod>
                  <iterativeness>it0</iterativeness>
                 </gram>
                 <val_frame.rf>v#v-w2310f1</val_frame.rf>
                 <children>
                  <LM id="t-mf930709-001-p3s2w23">
                   <a>
                    <lex.rf>a#a-mf930709-001-p3s2w23</lex.rf>
                   </a>
                   <nodetype>complex</nodetype>
                   <t_lemma>Havel</t_lemma>
                   <functor>ACT</functor>
                   <tfa>t</tfa>
                   <deepord>16</deepord>
                   <is_name_of_person>1</is_name_of_person>
                   <gram>
                    <sempos>n.denot</sempos>
                    <gender>anim</gender>
                    <number>sg</number>
                   </gram>
                  </LM>
                  <LM id="t-mf930709-001-p3s2w22">
                   <a>
                    <lex.rf>a#a-mf930709-001-p3s2w22</lex.rf>
                   </a>
                   <nodetype>complex</nodetype>
                   <t_lemma>který</t_lemma>
                   <functor>PAT</functor>
                   <tfa>t</tfa>
                   <deepord>17</deepord>
                   <gram>
                    <sempos>n.pron.indef</sempos>
                    <gender>inher</gender>
                    <number>inher</number>
                    <indeftype>relat</indeftype>
                    <person>inher</person>
                   </gram>
                   <coref_gram.rf>t-mf930709-001-p3s2w18</coref_gram.rf>
                  </LM>
                  <LM id="t-mf930709-001-p3s2a0">
                   <nodetype>qcomplex</nodetype>
                   <is_generated>1</is_generated>
                   <t_lemma>#Gen</t_lemma>
                   <functor>ADDR</functor>
                   <tfa>t</tfa>
                   <deepord>18</deepord>
                  </LM>
                 </children>
                </LM>
               </children>
              </LM>
             </children>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p3s3">
   <atree.rf>a#a-mf930709-001-p3s3</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p3s3w12">
     <a>
      <lex.rf>a#a-mf930709-001-p3s3w12</lex.rf>
      <aux.rf>a#a-mf930709-001-p3s3w11</aux.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>zahájit</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>9</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>hrt</deontmod>
      <tense>sim</tense>
      <aspect>cpl</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w8784f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p3s3w2">
       <a>
        <lex.rf>a#a-mf930709-001-p3s3w2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>soud</t_lemma>
       <functor>ACT</functor>
       <tfa>c</tfa>
       <deepord>1</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s3w1">
         <a>
          <lex.rf>a#a-mf930709-001-p3s3w1</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>ústavní</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>2</deepord>
         <gram>
          <sempos>adj.denot</sempos>
          <degcmp>pos</degcmp>
          <negation>neg0</negation>
         </gram>
        </LM>
        <LM id="t-mf930709-001-p3s3w5">
         <a>
          <lex.rf>a#a-mf930709-001-p3s3w5</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>být</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>4</deepord>
         <gram>
          <sempos>v</sempos>
          <verbmod>ind</verbmod>
          <deontmod>decl</deontmod>
          <tense>post</tense>
          <aspect>proc</aspect>
          <resultative>res0</resultative>
          <dispmod>disp0</dispmod>
          <iterativeness>it0</iterativeness>
         </gram>
         <val_frame.rf>v#v-w243f1</val_frame.rf>
         <children>
          <LM id="t-mf930709-001-p3s3w4">
           <a>
            <lex.rf>a#a-mf930709-001-p3s3w4</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>který</t_lemma>
           <functor>ACT</functor>
           <tfa>t</tfa>
           <deepord>3</deepord>
           <gram>
            <sempos>n.pron.indef</sempos>
            <gender>inher</gender>
            <number>inher</number>
            <indeftype>relat</indeftype>
            <person>inher</person>
           </gram>
           <coref_gram.rf>t-mf930709-001-p3s3w2</coref_gram.rf>
          </LM>
          <LM id="t-mf930709-001-p3s3w7">
           <a>
            <lex.rf>a#a-mf930709-001-p3s3w7</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>orgán</t_lemma>
           <functor>PAT</functor>
           <tfa>f</tfa>
           <deepord>5</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>inan</gender>
            <number>sg</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p3s3w6">
             <a>
              <lex.rf>a#a-mf930709-001-p3s3w6</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>soudní</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>6</deepord>
             <gram>
              <sempos>adj.denot</sempos>
              <degcmp>pos</degcmp>
              <negation>neg0</negation>
             </gram>
            </LM>
            <LM id="t-mf930709-001-p3s3w8">
             <a>
              <lex.rf>a#a-mf930709-001-p3s3w8</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>ochrana</t_lemma>
             <functor>APP</functor>
             <tfa>f</tfa>
             <deepord>7</deepord>
             <gram>
              <sempos>n.denot</sempos>
              <gender>fem</gender>
              <number>sg</number>
             </gram>
             <children>
              <LM id="t-mf930709-001-p3s3w9">
               <a>
                <lex.rf>a#a-mf930709-001-p3s3w9</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>ústavnost</t_lemma>
               <functor>PAT</functor>
               <tfa>f</tfa>
               <deepord>8</deepord>
               <gram>
                <sempos>n.denot.neg</sempos>
                <gender>fem</gender>
                <number>sg</number>
                <negation>neg0</negation>
               </gram>
              </LM>
             </children>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
      <LM id="t-mf930709-001-p3s3w13">
       <a>
        <lex.rf>a#a-mf930709-001-p3s3w13</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>činnost</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>10</deepord>
       <gram>
        <sempos>n.denot.neg</sempos>
        <gender>fem</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p3s3w15">
       <a>
        <lex.rf>a#a-mf930709-001-p3s3w15</lex.rf>
        <aux.rf>a#a-mf930709-001-p3s3w14</aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>Brno</t_lemma>
       <functor>LOC</functor>
       <subfunctor>basic</subfunctor>
       <tfa>f</tfa>
       <deepord>11</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>neut</gender>
        <number>sg</number>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p3s3w18">
       <a>
        <lex.rf>a#a-mf930709-001-p3s3w18</lex.rf>
        <aux.rf>a#a-mf930709-001-p3s3w17</aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>září</t_lemma>
       <functor>TWHEN</functor>
       <subfunctor>basic</subfunctor>
       <tfa>f</tfa>
       <deepord>12</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>neut</gender>
        <number>sg</number>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p3s3w16">
       <a>
        <lex.rf>a#a-mf930709-001-p3s3w16</lex.rf>
       </a>
       <nodetype>atom</nodetype>
       <t_lemma>zřejmě</t_lemma>
       <functor>MOD</functor>
       <tfa>f</tfa>
       <deepord>13</deepord>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p3s4">
   <atree.rf>a#a-mf930709-001-p3s4</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p3s4w4">
     <a>
      <lex.rf>a#a-mf930709-001-p3s4w4</lex.rf>
      <aux.rf>a#a-mf930709-001-p3s4w3</aux.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>skládat_se</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>3</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>decl</deontmod>
      <tense>sim</tense>
      <aspect>proc</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w6105f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p3s4w2">
       <a>
        <lex.rf>a#a-mf930709-001-p3s4w2</lex.rf>
        <aux.rf>a#a-mf930709-001-p3s4w1</aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>ústava</t_lemma>
       <functor>CRIT</functor>
       <tfa>t</tfa>
       <deepord>1</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>fem</gender>
        <number>sg</number>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p3s4a0">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <tfa>t</tfa>
       <deepord>2</deepord>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>inan</gender>
        <number>sg</number>
        <person>3</person>
        <politeness>basic</politeness>
       </gram>
       <coref_text.rf>t-mf930709-001-p3s3w4</coref_text.rf>
      </LM>
      <LM id="t-mf930709-001-p3s4w7">
       <a>
        <lex.rf>a#a-mf930709-001-p3s4w7</lex.rf>
        <aux.rf>a#a-mf930709-001-p3s4w5</aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>soudce</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>4</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>pl</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s4w6">
         <a>
          <lex.rf>a#a-mf930709-001-p3s4w6</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>15</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>5</deepord>
         <gram>
          <sempos>adj.quant.def</sempos>
          <numertype>basic</numertype>
         </gram>
        </LM>
        <LM id="t-mf930709-001-p3s4w9">
         <a>
          <lex.rf>a#a-mf930709-001-p3s4w9</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>jmenovaný</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>6</deepord>
         <gram>
          <sempos>adj.denot</sempos>
          <degcmp>pos</degcmp>
          <negation>neg0</negation>
         </gram>
         <children>
          <LM id="t-mf930709-001-p3s4w12">
           <a>
            <lex.rf>a#a-mf930709-001-p3s4w12</lex.rf>
            <aux.rf>a#a-mf930709-001-p3s4w10</aux.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>rok</t_lemma>
           <functor>THL</functor>
           <tfa>f</tfa>
           <deepord>7</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>neut</gender>
            <number>pl</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p3s4w11">
             <a>
              <lex.rf>a#a-mf930709-001-p3s4w11</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>deset</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>8</deepord>
             <gram>
              <sempos>adj.quant.def</sempos>
              <numertype>basic</numertype>
             </gram>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p3s5">
   <atree.rf>a#a-mf930709-001-p3s5</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p3s5w4">
     <a>
      <lex.rf>a#a-mf930709-001-p3s5w4</lex.rf>
      <aux.rf>
       <LM>a#a-mf930709-001-p3s5w2</LM>
       <LM>a#a-mf930709-001-p3s5w3</LM>
      </aux.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>ujmout_se</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>2</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>poss</deontmod>
      <tense>sim</tense>
      <aspect>cpl</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w7088f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p3s5w1">
       <a>
        <lex.rf>a#a-mf930709-001-p3s5w1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>soud</t_lemma>
       <functor>ACT</functor>
       <tfa>t</tfa>
       <deepord>1</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p3s5w5">
       <a>
        <lex.rf>a#a-mf930709-001-p3s5w5</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>činnost</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>3</deepord>
       <gram>
        <sempos>n.denot.neg</sempos>
        <gender>fem</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p3s5w6">
       <a>
        <lex.rf>a#a-mf930709-001-p3s5w6</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>složení</t_lemma>
       <functor>MANN</functor>
       <tfa>f</tfa>
       <deepord>5</deepord>
       <gram>
        <sempos>n.denot.neg</sempos>
        <gender>neut</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <val_frame.rf>v#v-w6175f2</val_frame.rf>
       <children>
        <LM id="t-mf930709-001-p3s5a0">
         <nodetype>qcomplex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Gen</t_lemma>
         <functor>ACT</functor>
         <tfa>t</tfa>
         <deepord>4</deepord>
        </LM>
        <LM id="t-mf930709-001-p3s5w7">
         <a>
          <lex.rf>a#a-mf930709-001-p3s5w7</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>slib</t_lemma>
         <functor>PAT</functor>
         <tfa>f</tfa>
         <deepord>6</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>inan</gender>
          <number>sg</number>
         </gram>
         <children>
          <LM id="t-mf930709-001-p3s5w9">
           <a>
            <lex.rf>a#a-mf930709-001-p3s5w9</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>soudce</t_lemma>
           <functor>ACT</functor>
           <tfa>f</tfa>
           <deepord>7</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>anim</gender>
            <number>sg</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p3s5w8">
             <a>
              <lex.rf>a#a-mf930709-001-p3s5w8</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>dvanáct</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>8</deepord>
             <gram>
              <sempos>adj.quant.def</sempos>
              <numertype>ord</numertype>
             </gram>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p3s6">
   <atree.rf>a#a-mf930709-001-p3s6</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p3s6w4">
     <a>
      <lex.rf>a#a-mf930709-001-p3s6w4</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>být</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>4</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>decl</deontmod>
      <tense>sim</tense>
      <aspect>proc</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w243f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p3s6w1">
       <a>
        <lex.rf>a#a-mf930709-001-p3s6w1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>funkce</t_lemma>
       <functor>ACT</functor>
       <tfa>t</tfa>
       <deepord>3</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>fem</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s6w3">
         <a>
          <lex.rf>a#a-mf930709-001-p3s6w3</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>soudce</t_lemma>
         <functor>APP</functor>
         <tfa>t</tfa>
         <deepord>2</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>anim</gender>
          <number>sg</number>
         </gram>
         <children>
          <LM id="t-mf930709-001-p3s6w2">
           <a>
            <lex.rf>a#a-mf930709-001-p3s6w2</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>ústavní</t_lemma>
           <functor>RSTR</functor>
           <tfa>t</tfa>
           <deepord>1</deepord>
           <gram>
            <sempos>adj.denot</sempos>
            <degcmp>pos</degcmp>
            <negation>neg0</negation>
           </gram>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
      <LM id="t-mf930709-001-p3s6w5">
       <a>
        <lex.rf>a#a-mf930709-001-p3s6w5</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>slučitelný</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>5</deepord>
       <gram>
        <sempos>adj.denot</sempos>
        <degcmp>pos</degcmp>
        <negation>neg1</negation>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s6w7">
         <a>
          <lex.rf>a#a-mf930709-001-p3s6w7</lex.rf>
          <aux.rf>a#a-mf930709-001-p3s6w6</aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>členství</t_lemma>
         <functor>PAT</functor>
         <tfa>f</tfa>
         <deepord>6</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>neut</gender>
          <number>sg</number>
         </gram>
         <children>
          <LM id="t-mf930709-001-p3s6w10">
           <a>
            <lex.rf>a#a-mf930709-001-p3s6w10</lex.rf>
            <aux.rf>a#a-mf930709-001-p3s6w8</aux.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>strana</t_lemma>
           <functor>LOC</functor>
           <subfunctor>basic</subfunctor>
           <tfa>f</tfa>
           <deepord>7</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>fem</gender>
            <number>pl</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p3s6w9">
             <a>
              <lex.rf>a#a-mf930709-001-p3s6w9</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>politický</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>8</deepord>
             <gram>
              <sempos>adj.denot</sempos>
              <degcmp>pos</degcmp>
              <negation>neg0</negation>
             </gram>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p3s7">
   <atree.rf>a#a-mf930709-001-p3s7</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p3s7w4">
     <a>
      <lex.rf>a#a-mf930709-001-p3s7w4</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>být</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>4</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>decl</deontmod>
      <tense>post</tense>
      <aspect>proc</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w243f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p3s7w2">
       <a>
        <lex.rf>a#a-mf930709-001-p3s7w2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>plat</t_lemma>
       <functor>ACT</functor>
       <tfa>c</tfa>
       <deepord>2</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s7w3">
         <a>
          <lex.rf>a#a-mf930709-001-p3s7w3</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>soudce</t_lemma>
         <functor>APP</functor>
         <tfa>t</tfa>
         <deepord>1</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>anim</gender>
          <number>pl</number>
         </gram>
        </LM>
        <LM id="t-mf930709-001-p3s7w1">
         <a>
          <lex.rf>a#a-mf930709-001-p3s7w1</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>základní</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>3</deepord>
         <gram>
          <sempos>adj.denot</sempos>
          <degcmp>pos</degcmp>
          <negation>neg0</negation>
         </gram>
        </LM>
       </children>
      </LM>
      <LM id="t-mf930709-001-p3s7w6">
       <a>
        <lex.rf>a#a-mf930709-001-p3s7w6</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>tisíc</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>5</deepord>
       <gram>
        <sempos>n.quant.def</sempos>
        <gender>inan</gender>
        <number>sg</number>
        <numertype>basic</numertype>
       </gram>
       <children>
        <LM id="t-mf930709-001-p3s7w7">
         <a>
          <lex.rf>a#a-mf930709-001-p3s7w7</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>koruna</t_lemma>
         <functor>MAT</functor>
         <tfa>f</tfa>
         <deepord>6</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>fem</gender>
          <number>pl</number>
         </gram>
        </LM>
        <LM id="t-mf930709-001-p3s7w5">
         <a>
          <lex.rf>a#a-mf930709-001-p3s7w5</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>25</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>7</deepord>
         <gram>
          <sempos>adj.quant.def</sempos>
          <numertype>basic</numertype>
         </gram>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p4s1">
      <mwes>      
          <st id="s-mf930709-001-l13">
              <lexicon-id>s##person</lexicon-id>
              <t.rf>
                  <LM>t-mf930709-001-p4s1w12</LM>
                  <LM>t-mf930709-001-p4s1w13</LM>
              </t.rf>
          </st>
          <st id="s-mf930709-001-l18">
              <lexicon-id>s##person</lexicon-id>
              <t.rf>         
                  <LM>t-mf930709-001-p4s1w22</LM>
                  <LM>t-mf930709-001-p4s1w23</LM>
              </t.rf>
          </st>
          <st id="s-mf930709-001-l23">
              <lexicon-id>s##person</lexicon-id>
              <t.rf>
                  <LM>t-mf930709-001-p4s1w32</LM>
                  <LM>t-mf930709-001-p4s1w33</LM>
              </t.rf>
          </st>
          <st id="s-mf930709-001-l29">
              <lexicon-id>s##person</lexicon-id>
              <t.rf>
                  <LM>t-mf930709-001-p4s1w45</LM>
                  <LM>t-mf930709-001-p4s1w46</LM>
              </t.rf>
          </st>
          <st id="s-mf930709-001-l32">
              <lexicon-id>s##person</lexicon-id>
              <t.rf>
                  <LM>t-mf930709-001-p4s1w53</LM>
                  <LM>t-mf930709-001-p4s1w54</LM>
              </t.rf>
          </st>
          <st id="s-mf930709-001-l35">
              <lexicon-id>s##person</lexicon-id>
              <t.rf>
                  <LM>t-mf930709-001-p4s1w56</LM>
                  <LM>t-mf930709-001-p4s1w57</LM>
              </t.rf>
          </st>
          <st id="s-mf930709-001-l38">
              <lexicon-id>s##person</lexicon-id>
              <t.rf>
                  <LM>t-mf930709-001-p4s1w59</LM>
                  <LM>t-mf930709-001-p4s1w60</LM>
              </t.rf>
          </st>
          <st id="s-mf930709-001-l43">
              <lexicon-id>s##person</lexicon-id>
              <t.rf>
                  <LM>t-mf930709-001-p4s1w63</LM>
                  <LM>t-mf930709-001-p4s1w64</LM>
              </t.rf>
          </st>
      </mwes>
    <atree.rf>a#a-mf930709-001-p4s1</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p4s1w5">
     <a>
      <lex.rf>a#a-mf930709-001-p4s1w5</lex.rf>
      <aux.rf>
       <LM>a#a-mf930709-001-p4s1w4</LM>
       <LM>a#a-mf930709-001-p4s1w2</LM>
       <LM>a#a-mf930709-001-p4s1w3</LM>
      </aux.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>stát_se</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>2</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>cdn</verbmod>
      <deontmod>hrt</deontmod>
      <tense>sim</tense>
      <aspect>proc</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w6496f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p4s1w1">
       <a>
        <lex.rf>a#a-mf930709-001-p4s1w1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>soudce</t_lemma>
       <functor>PAT</functor>
       <tfa>t</tfa>
       <deepord>1</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>pl</number>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p4s1w47">
       <a>
        <lex.rf>a#a-mf930709-001-p4s1w47</lex.rf>
       </a>
       <nodetype>coap</nodetype>
       <t_lemma>a</t_lemma>
       <functor>CONJ</functor>
       <deepord>36</deepord>
       <sentmod>enunc</sentmod>
       <children>
        <LM id="t-mf930709-001-p4s1a0">
         <nodetype>coap</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Separ</t_lemma>
         <functor>APPS</functor>
         <is_member>1</is_member>
         <deepord>9</deepord>
         <children>
          <LM id="t-mf930709-001-p4s1w8">
           <a>
            <lex.rf>a#a-mf930709-001-p4s1w8</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>člen</t_lemma>
           <functor>ACT</functor>
           <is_member>1</is_member>
           <tfa>f</tfa>
           <deepord>3</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>anim</gender>
            <number>pl</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p4s1w10">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w10</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>soud</t_lemma>
             <functor>APP</functor>
             <tfa>f</tfa>
             <deepord>4</deepord>
             <gram>
              <sempos>n.denot</sempos>
              <gender>inan</gender>
              <number>sg</number>
             </gram>
             <children>
              <LM id="t-mf930709-001-p4s1w9">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w9</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>ústavní</t_lemma>
               <functor>RSTR</functor>
               <tfa>f</tfa>
               <deepord>5</deepord>
               <gram>
                <sempos>adj.denot</sempos>
                <degcmp>pos</degcmp>
                <negation>neg0</negation>
               </gram>
              </LM>
              <LM id="t-mf930709-001-p4s1w11">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w11</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>ČSFR</t_lemma>
               <functor>APP</functor>
               <tfa>f</tfa>
               <deepord>6</deepord>
               <gram>
                <sempos>n.denot</sempos>
                <gender>fem</gender>
                <number>nr</number>
               </gram>
              </LM>
             </children>
            </LM>
            <LM id="t-mf930709-001-p4s1w7">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w7</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>bývalý</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>7</deepord>
             <gram>
              <sempos>adj.denot</sempos>
              <degcmp>pos</degcmp>
              <negation>neg0</negation>
             </gram>
            </LM>
            <LM id="t-mf930709-001-p4s1w6">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w6</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>pět</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>8</deepord>
             <gram>
              <sempos>adj.quant.def</sempos>
              <numertype>basic</numertype>
             </gram>
            </LM>
           </children>
          </LM>
          <LM id="t-mf930709-001-p4s1w44">
           <a>
            <lex.rf>a#a-mf930709-001-p4s1w44</lex.rf>
           </a>
           <nodetype>coap</nodetype>
           <t_lemma>a</t_lemma>
           <functor>CONJ</functor>
           <is_member>1</is_member>
           <deepord>33</deepord>
           <children>
            <LM id="t-mf930709-001-p4s1w14">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w14</lex.rf>
             </a>
             <nodetype>coap</nodetype>
             <t_lemma>#Bracket</t_lemma>
             <functor>APPS</functor>
             <is_member>1</is_member>
             <is_parenthesis>1</is_parenthesis>
             <deepord>12</deepord>
             <children>
              <LM id="t-mf930709-001-p4s1w13">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w13</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Kessler</t_lemma>
               <functor>ACT</functor>
               <is_member>1</is_member>
               <tfa>f</tfa>
               <deepord>10</deepord>
               <is_name_of_person>1</is_name_of_person>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
               <children>
                <LM id="t-mf930709-001-p4s1w12">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w12</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>Zdeněk</t_lemma>
                 <functor>RSTR</functor>
                 <tfa>f</tfa>
                 <deepord>11</deepord>
                 <is_name_of_person>1</is_name_of_person>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>anim</gender>
                  <number>sg</number>
                 </gram>
                </LM>
               </children>
              </LM>
              <LM id="t-mf930709-001-p4s1w16">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w16</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>poslanec</t_lemma>
               <functor>PAR</functor>
               <is_member>1</is_member>
               <is_parenthesis>1</is_parenthesis>
               <tfa>f</tfa>
               <deepord>14</deepord>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
               <children>
                <LM id="t-mf930709-001-p4s1w15">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w15</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>brzy</t_lemma>
                 <functor>TWHEN</functor>
                 <subfunctor>basic</subfunctor>
                 <is_parenthesis>1</is_parenthesis>
                 <tfa>c</tfa>
                 <deepord>13</deepord>
                 <gram>
                  <sempos>adv.denot.grad.nneg</sempos>
                  <degcmp>comp</degcmp>
                 </gram>
                </LM>
                <LM id="t-mf930709-001-p4s1w17">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w17</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>FS</t_lemma>
                 <functor>APP</functor>
                 <is_parenthesis>1</is_parenthesis>
                 <tfa>f</tfa>
                 <deepord>15</deepord>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>neut</gender>
                  <number>nr</number>
                 </gram>
                </LM>
                <LM id="t-mf930709-001-p4s1w19">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w19</lex.rf>
                  <aux.rf>a#a-mf930709-001-p4s1w18</aux.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>ODS</t_lemma>
                 <functor>SUBS</functor>
                 <is_parenthesis>1</is_parenthesis>
                 <tfa>f</tfa>
                 <deepord>16</deepord>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>fem</gender>
                  <number>nr</number>
                 </gram>
                </LM>
               </children>
              </LM>
             </children>
            </LM>
            <LM id="t-mf930709-001-p4s1w24">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w24</lex.rf>
             </a>
             <nodetype>coap</nodetype>
             <t_lemma>#Bracket</t_lemma>
             <functor>APPS</functor>
             <is_member>1</is_member>
             <is_parenthesis>1</is_parenthesis>
             <deepord>19</deepord>
             <children>
              <LM id="t-mf930709-001-p4s1w23">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w23</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Ševčík</t_lemma>
               <functor>ACT</functor>
               <is_member>1</is_member>
               <tfa>f</tfa>
               <deepord>17</deepord>
               <is_name_of_person>1</is_name_of_person>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
               <children>
                <LM id="t-mf930709-001-p4s1w22">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w22</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>Vlastimil</t_lemma>
                 <functor>RSTR</functor>
                 <tfa>f</tfa>
                 <deepord>18</deepord>
                 <is_name_of_person>1</is_name_of_person>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>anim</gender>
                  <number>sg</number>
                 </gram>
                </LM>
               </children>
              </LM>
              <LM id="t-mf930709-001-p4s1w26">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w26</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>poslanec</t_lemma>
               <functor>PAR</functor>
               <is_member>1</is_member>
               <is_parenthesis>1</is_parenthesis>
               <tfa>f</tfa>
               <deepord>21</deepord>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
               <children>
                <LM id="t-mf930709-001-p4s1w25">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w25</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>předtím</t_lemma>
                 <functor>TWHEN</functor>
                 <subfunctor>basic</subfunctor>
                 <is_parenthesis>1</is_parenthesis>
                 <tfa>c</tfa>
                 <deepord>20</deepord>
                 <gram>
                  <sempos>adv.pron.def</sempos>
                 </gram>
                </LM>
                <LM id="t-mf930709-001-p4s1w27">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w27</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>FS</t_lemma>
                 <functor>APP</functor>
                 <is_parenthesis>1</is_parenthesis>
                 <tfa>f</tfa>
                 <deepord>22</deepord>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>neut</gender>
                  <number>nr</number>
                 </gram>
                </LM>
                <LM id="t-mf930709-001-p4s1w29">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w29</lex.rf>
                  <aux.rf>a#a-mf930709-001-p4s1w28</aux.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>OH</t_lemma>
                 <functor>SUBS</functor>
                 <is_parenthesis>1</is_parenthesis>
                 <tfa>f</tfa>
                 <deepord>23</deepord>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>neut</gender>
                  <number>nr</number>
                 </gram>
                </LM>
               </children>
              </LM>
             </children>
            </LM>
            <LM id="t-mf930709-001-p4s1w34">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w34</lex.rf>
             </a>
             <nodetype>coap</nodetype>
             <t_lemma>#Bracket</t_lemma>
             <functor>APPS</functor>
             <is_member>1</is_member>
             <is_parenthesis>1</is_parenthesis>
             <deepord>26</deepord>
             <children>
              <LM id="t-mf930709-001-p4s1w33">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w33</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Procházka</t_lemma>
               <functor>ACT</functor>
               <is_member>1</is_member>
               <tfa>f</tfa>
               <deepord>24</deepord>
               <is_name_of_person>1</is_name_of_person>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
               <children>
                <LM id="t-mf930709-001-p4s1w32">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w32</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>Antonín</t_lemma>
                 <functor>RSTR</functor>
                 <tfa>f</tfa>
                 <deepord>25</deepord>
                 <is_name_of_person>1</is_name_of_person>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>anim</gender>
                  <number>sg</number>
                 </gram>
                </LM>
               </children>
              </LM>
              <LM id="t-mf930709-001-p4s1w36">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w36</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>poslanec</t_lemma>
               <functor>PAR</functor>
               <is_member>1</is_member>
               <is_parenthesis>1</is_parenthesis>
               <tfa>f</tfa>
               <deepord>28</deepord>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
               <children>
                <LM id="t-mf930709-001-p4s1w35">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w35</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>brzy</t_lemma>
                 <functor>TWHEN</functor>
                 <subfunctor>basic</subfunctor>
                 <is_parenthesis>1</is_parenthesis>
                 <tfa>c</tfa>
                 <deepord>27</deepord>
                 <gram>
                  <sempos>adv.denot.grad.nneg</sempos>
                  <degcmp>comp</degcmp>
                 </gram>
                </LM>
                <LM id="t-mf930709-001-p4s1w37">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w37</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>ČNR</t_lemma>
                 <functor>APP</functor>
                 <is_parenthesis>1</is_parenthesis>
                 <tfa>f</tfa>
                 <deepord>29</deepord>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>fem</gender>
                  <number>nr</number>
                 </gram>
                </LM>
                <LM id="t-mf930709-001-p4s1w39">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s1w39</lex.rf>
                  <aux.rf>a#a-mf930709-001-p4s1w38</aux.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>KDS</t_lemma>
                 <functor>SUBS</functor>
                 <is_parenthesis>1</is_parenthesis>
                 <tfa>f</tfa>
                 <deepord>30</deepord>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>fem</gender>
                  <number>nr</number>
                 </gram>
                </LM>
               </children>
              </LM>
             </children>
            </LM>
            <LM id="t-mf930709-001-p4s1w43">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w43</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Güttler</t_lemma>
             <functor>ACT</functor>
             <is_member>1</is_member>
             <tfa>f</tfa>
             <deepord>31</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>anim</gender>
              <number>sg</number>
             </gram>
             <children>
              <LM id="t-mf930709-001-p4s1w42">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w42</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Vojna</t_lemma>
               <functor>RSTR</functor>
               <tfa>f</tfa>
               <deepord>32</deepord>
               <is_name_of_person>1</is_name_of_person>
               <gram>
                <sempos>n.denot</sempos>
                <gender>fem</gender>
                <number>pl</number>
               </gram>
              </LM>
             </children>
            </LM>
            <LM id="t-mf930709-001-p4s1w46">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w46</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Mates</t_lemma>
             <functor>ACT</functor>
             <is_member>1</is_member>
             <tfa>f</tfa>
             <deepord>34</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>anim</gender>
              <number>sg</number>
             </gram>
             <children>
              <LM id="t-mf930709-001-p4s1w45">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w45</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Pavel</t_lemma>
               <functor>RSTR</functor>
               <tfa>f</tfa>
               <deepord>35</deepord>
               <is_name_of_person>1</is_name_of_person>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
              </LM>
             </children>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
        <LM id="t-mf930709-001-p4s1w52">
         <a>
          <lex.rf>a#a-mf930709-001-p4s1w52</lex.rf>
         </a>
         <nodetype>coap</nodetype>
         <t_lemma>#Dash</t_lemma>
         <functor>APPS</functor>
         <is_member>1</is_member>
         <deepord>41</deepord>
         <children>
          <LM id="t-mf930709-001-p4s1w50">
           <a>
            <lex.rf>a#a-mf930709-001-p4s1w50</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>učitel</t_lemma>
           <functor>ACT</functor>
           <is_member>1</is_member>
           <tfa>f</tfa>
           <deepord>37</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>anim</gender>
            <number>pl</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p4s1w51">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w51</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>právo</t_lemma>
             <functor>PAT</functor>
             <tfa>f</tfa>
             <deepord>38</deepord>
             <gram>
              <sempos>n.denot</sempos>
              <gender>neut</gender>
              <number>sg</number>
             </gram>
            </LM>
            <LM id="t-mf930709-001-p4s1w49">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w49</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>vysokoškolský</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>39</deepord>
             <gram>
              <sempos>adj.denot</sempos>
              <degcmp>pos</degcmp>
              <negation>neg0</negation>
             </gram>
            </LM>
            <LM id="t-mf930709-001-p4s1w48">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w48</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>čtyři</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>40</deepord>
             <gram>
              <sempos>adj.quant.def</sempos>
              <numertype>basic</numertype>
             </gram>
            </LM>
           </children>
          </LM>
          <LM id="t-mf930709-001-p4s1w61">
           <a>
            <lex.rf>a#a-mf930709-001-p4s1w61</lex.rf>
           </a>
           <nodetype>coap</nodetype>
           <t_lemma>a</t_lemma>
           <functor>CONJ</functor>
           <is_member>1</is_member>
           <deepord>48</deepord>
           <children>
            <LM id="t-mf930709-001-p4s1w54">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w54</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Klokočka</t_lemma>
             <functor>ACT</functor>
             <is_member>1</is_member>
             <tfa>f</tfa>
             <deepord>42</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>anim</gender>
              <number>sg</number>
             </gram>
             <children>
              <LM id="t-mf930709-001-p4s1w53">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w53</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Vladimír</t_lemma>
               <functor>RSTR</functor>
               <tfa>f</tfa>
               <deepord>43</deepord>
               <is_name_of_person>1</is_name_of_person>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
              </LM>
             </children>
            </LM>
            <LM id="t-mf930709-001-p4s1w57">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w57</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Cepl</t_lemma>
             <functor>ACT</functor>
             <is_member>1</is_member>
             <tfa>f</tfa>
             <deepord>44</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>anim</gender>
              <number>sg</number>
             </gram>
             <children>
              <LM id="t-mf930709-001-p4s1w56">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w56</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Vojtěch</t_lemma>
               <functor>RSTR</functor>
               <tfa>f</tfa>
               <deepord>45</deepord>
               <is_name_of_person>1</is_name_of_person>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
              </LM>
             </children>
            </LM>
            <LM id="t-mf930709-001-p4s1w60">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w60</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Čermák</t_lemma>
             <functor>ACT</functor>
             <is_member>1</is_member>
             <tfa>f</tfa>
             <deepord>46</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>anim</gender>
              <number>sg</number>
             </gram>
             <children>
              <LM id="t-mf930709-001-p4s1w59">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w59</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Vladimír</t_lemma>
               <functor>RSTR</functor>
               <tfa>f</tfa>
               <deepord>47</deepord>
               <is_name_of_person>1</is_name_of_person>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
              </LM>
             </children>
            </LM>
            <LM id="t-mf930709-001-p4s1w64">
             <a>
              <lex.rf>a#a-mf930709-001-p4s1w64</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Holländer</t_lemma>
             <functor>ACT</functor>
             <is_member>1</is_member>
             <tfa>f</tfa>
             <deepord>49</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>anim</gender>
              <number>sg</number>
             </gram>
             <children>
              <LM id="t-mf930709-001-p4s1w63">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w63</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Pavol</t_lemma>
               <functor>RSTR</functor>
               <tfa>f</tfa>
               <deepord>50</deepord>
               <is_name_of_person>1</is_name_of_person>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
              </LM>
              <LM id="t-mf930709-001-p4s1w62">
               <a>
                <lex.rf>a#a-mf930709-001-p4s1w62</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Slovák</t_lemma>
               <functor>RSTR</functor>
               <tfa>f</tfa>
               <deepord>51</deepord>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>sg</number>
               </gram>
              </LM>
             </children>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p4s2">
   <atree.rf>a#a-mf930709-001-p4s2</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p4s2w14">
     <a>
      <lex.rf>a#a-mf930709-001-p4s2w14</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>být</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>12</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>decl</deontmod>
      <tense>sim</tense>
      <aspect>proc</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w243f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p4s2w4">
       <a>
        <lex.rf>a#a-mf930709-001-p4s2w4</lex.rf>
       </a>
       <nodetype>coap</nodetype>
       <t_lemma>#Comma</t_lemma>
       <functor>APPS</functor>
       <deepord>4</deepord>
       <children>
        <LM id="t-mf930709-001-p4s2w3">
         <a>
          <lex.rf>a#a-mf930709-001-p4s2w3</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>kandidát</t_lemma>
         <functor>ACT</functor>
         <is_member>1</is_member>
         <tfa>c</tfa>
         <deepord>1</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>anim</gender>
          <number>pl</number>
         </gram>
         <children>
          <LM id="t-mf930709-001-p4s2w2">
           <a>
            <lex.rf>a#a-mf930709-001-p4s2w2</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>další</t_lemma>
           <functor>RSTR</functor>
           <tfa>f</tfa>
           <deepord>2</deepord>
           <gram>
            <sempos>adj.denot</sempos>
            <degcmp>pos</degcmp>
            <negation>neg0</negation>
           </gram>
          </LM>
          <LM id="t-mf930709-001-p4s2w1">
           <a>
            <lex.rf>a#a-mf930709-001-p4s2w1</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>tři</t_lemma>
           <functor>RSTR</functor>
           <tfa>f</tfa>
           <deepord>3</deepord>
           <gram>
            <sempos>adj.quant.def</sempos>
            <numertype>basic</numertype>
           </gram>
          </LM>
         </children>
        </LM>
        <LM id="t-mf930709-001-p4s2w10">
         <a>
          <lex.rf>a#a-mf930709-001-p4s2w10</lex.rf>
         </a>
         <nodetype>coap</nodetype>
         <t_lemma>a</t_lemma>
         <functor>CONJ</functor>
         <is_member>1</is_member>
         <deepord>9</deepord>
         <children>
          <LM id="t-mf930709-001-p4s2w6">
           <a>
            <lex.rf>a#a-mf930709-001-p4s2w6</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>Brožová</t_lemma>
           <functor>ACT</functor>
           <is_member>1</is_member>
           <tfa>c</tfa>
           <deepord>5</deepord>
           <is_name_of_person>1</is_name_of_person>
           <gram>
            <sempos>n.denot</sempos>
            <gender>fem</gender>
            <number>sg</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p4s2w5">
             <a>
              <lex.rf>a#a-mf930709-001-p4s2w5</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Iva</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>6</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>fem</gender>
              <number>sg</number>
             </gram>
            </LM>
           </children>
          </LM>
          <LM id="t-mf930709-001-p4s2w9">
           <a>
            <lex.rf>a#a-mf930709-001-p4s2w9</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>Holeček</t_lemma>
           <functor>ACT</functor>
           <is_member>1</is_member>
           <tfa>c</tfa>
           <deepord>7</deepord>
           <is_name_of_person>1</is_name_of_person>
           <gram>
            <sempos>n.denot</sempos>
            <gender>anim</gender>
            <number>sg</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p4s2w8">
             <a>
              <lex.rf>a#a-mf930709-001-p4s2w8</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Miloš</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>8</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>anim</gender>
              <number>sg</number>
             </gram>
            </LM>
           </children>
          </LM>
          <LM id="t-mf930709-001-p4s2w12">
           <a>
            <lex.rf>a#a-mf930709-001-p4s2w12</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>Jurka</t_lemma>
           <functor>ACT</functor>
           <is_member>1</is_member>
           <tfa>c</tfa>
           <deepord>10</deepord>
           <is_name_of_person>1</is_name_of_person>
           <gram>
            <sempos>n.denot</sempos>
            <gender>anim</gender>
            <number>sg</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p4s2w11">
             <a>
              <lex.rf>a#a-mf930709-001-p4s2w11</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Vladimír</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>11</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>anim</gender>
              <number>sg</number>
             </gram>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
      <LM id="t-mf930709-001-p4s2w15">
       <a>
        <lex.rf>a#a-mf930709-001-p4s2w15</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>soudce</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>13</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>pl</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p4s2w17">
         <a>
          <lex.rf>a#a-mf930709-001-p4s2w17</lex.rf>
         </a>
         <nodetype>coap</nodetype>
         <t_lemma>a</t_lemma>
         <functor>CONJ</functor>
         <deepord>16</deepord>
         <children>
          <LM id="t-mf930709-001-p4s2a0">
           <a>
            <lex.rf>a#a-mf930709-001-p4s2w19</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <is_generated>1</is_generated>
           <t_lemma>soud</t_lemma>
           <functor>APP</functor>
           <is_member>1</is_member>
           <tfa>f</tfa>
           <deepord>14</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>inan</gender>
            <number>sg</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p4s2w16">
             <a>
              <lex.rf>a#a-mf930709-001-p4s2w16</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>krajský</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>15</deepord>
             <gram>
              <sempos>adj.denot</sempos>
              <degcmp>pos</degcmp>
              <negation>neg0</negation>
             </gram>
            </LM>
           </children>
          </LM>
          <LM id="t-mf930709-001-p4s2w19">
           <a>
            <lex.rf>a#a-mf930709-001-p4s2w19</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>soud</t_lemma>
           <functor>APP</functor>
           <is_member>1</is_member>
           <tfa>t</tfa>
           <deepord>17</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>inan</gender>
            <number>sg</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p4s2w18">
             <a>
              <lex.rf>a#a-mf930709-001-p4s2w18</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>okresní</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>18</deepord>
             <gram>
              <sempos>adj.denot</sempos>
              <degcmp>pos</degcmp>
              <negation>neg0</negation>
             </gram>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p4s3">
   <atree.rf>a#a-mf930709-001-p4s3</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p4s3w3">
     <a>
      <lex.rf>a#a-mf930709-001-p4s3w3</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>být</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>3</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>decl</deontmod>
      <tense>sim</tense>
      <aspect>proc</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w243f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p4s3w2">
       <a>
        <lex.rf>a#a-mf930709-001-p4s3w2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>kandidát</t_lemma>
       <functor>PAT</functor>
       <tfa>c</tfa>
       <deepord>1</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p4s3w1">
         <a>
          <lex.rf>a#a-mf930709-001-p4s3w1</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>třináct</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>2</deepord>
         <gram>
          <sempos>adj.quant.def</sempos>
          <numertype>ord</numertype>
         </gram>
        </LM>
       </children>
      </LM>
      <LM id="t-mf930709-001-p4s3w7">
       <a>
        <lex.rf>a#a-mf930709-001-p4s3w7</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>Paul</t_lemma>
       <functor>ACT</functor>
       <tfa>f</tfa>
       <deepord>4</deepord>
       <is_name_of_person>1</is_name_of_person>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p4s3w6">
         <a>
          <lex.rf>a#a-mf930709-001-p4s3w6</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>Vladimír</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>5</deepord>
         <is_name_of_person>1</is_name_of_person>
         <gram>
          <sempos>n.denot</sempos>
          <gender>anim</gender>
          <number>sg</number>
         </gram>
        </LM>
        <LM id="t-mf930709-001-p4s3w5">
         <a>
          <lex.rf>a#a-mf930709-001-p4s3w5</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>právník</t_lemma>
         <functor>RSTR</functor>
         <tfa>f</tfa>
         <deepord>6</deepord>
         <gram>
          <sempos>n.denot</sempos>
          <gender>anim</gender>
          <number>sg</number>
         </gram>
         <children>
          <LM id="t-mf930709-001-p4s3w4">
           <a>
            <lex.rf>a#a-mf930709-001-p4s3w4</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>komerční</t_lemma>
           <functor>RSTR</functor>
           <tfa>f</tfa>
           <deepord>7</deepord>
           <gram>
            <sempos>adj.denot</sempos>
            <degcmp>pos</degcmp>
            <negation>neg0</negation>
           </gram>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="t-mf930709-001-p4s4">
   <atree.rf>a#a-mf930709-001-p4s4</atree.rf>
   <nodetype>root</nodetype>
   <deepord>0</deepord>
   <children>
    <LM id="t-mf930709-001-p4s4w2">
     <a>
      <lex.rf>a#a-mf930709-001-p4s4w2</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>schválit</t_lemma>
     <functor>PRED</functor>
     <tfa>f</tfa>
     <deepord>3</deepord>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <verbmod>ind</verbmod>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>cpl</aspect>
      <resultative>res0</resultative>
      <dispmod>disp0</dispmod>
      <iterativeness>it0</iterativeness>
     </gram>
     <val_frame.rf>v#v-w6054f1</val_frame.rf>
     <children>
      <LM id="t-mf930709-001-p4s4w1">
       <a>
        <lex.rf>a#a-mf930709-001-p4s4w1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>parlament</t_lemma>
       <functor>ACT</functor>
       <tfa>t</tfa>
       <deepord>1</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
       </gram>
      </LM>
      <LM id="t-mf930709-001-p4s4a0">
       <nodetype>atom</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#Neg</t_lemma>
       <functor>RHEM</functor>
       <tfa>f</tfa>
       <deepord>2</deepord>
      </LM>
      <LM id="t-mf930709-001-p4s4w3">
       <a>
        <lex.rf>a#a-mf930709-001-p4s4w3</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>kandidatura</t_lemma>
       <functor>PAT</functor>
       <tfa>f</tfa>
       <deepord>4</deepord>
       <gram>
        <sempos>n.denot</sempos>
        <gender>fem</gender>
        <number>sg</number>
       </gram>
       <children>
        <LM id="t-mf930709-001-p4s4w7">
         <a>
          <lex.rf>a#a-mf930709-001-p4s4w7</lex.rf>
         </a>
         <nodetype>coap</nodetype>
         <t_lemma>#Comma</t_lemma>
         <functor>APPS</functor>
         <deepord>8</deepord>
         <children>
          <LM id="t-mf930709-001-p4s4w6">
           <a>
            <lex.rf>a#a-mf930709-001-p4s4w6</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>Pelikánová</t_lemma>
           <functor>APP</functor>
           <is_member>1</is_member>
           <tfa>f</tfa>
           <deepord>5</deepord>
           <is_name_of_person>1</is_name_of_person>
           <gram>
            <sempos>n.denot</sempos>
            <gender>fem</gender>
            <number>sg</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p4s4w5">
             <a>
              <lex.rf>a#a-mf930709-001-p4s4w5</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Irena</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>6</deepord>
             <is_name_of_person>1</is_name_of_person>
             <gram>
              <sempos>n.denot</sempos>
              <gender>fem</gender>
              <number>sg</number>
             </gram>
            </LM>
            <LM id="t-mf930709-001-p4s4w4">
             <a>
              <lex.rf>a#a-mf930709-001-p4s4w4</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>docentka</t_lemma>
             <functor>RSTR</functor>
             <tfa>f</tfa>
             <deepord>7</deepord>
             <gram>
              <sempos>n.denot</sempos>
              <gender>fem</gender>
              <number>sg</number>
             </gram>
            </LM>
           </children>
          </LM>
          <LM id="t-mf930709-001-p4s4w8">
           <a>
            <lex.rf>a#a-mf930709-001-p4s4w8</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>členka</t_lemma>
           <functor>APP</functor>
           <is_member>1</is_member>
           <tfa>f</tfa>
           <deepord>9</deepord>
           <gram>
            <sempos>n.denot</sempos>
            <gender>fem</gender>
            <number>sg</number>
           </gram>
           <children>
            <LM id="t-mf930709-001-p4s4w9">
             <a>
              <lex.rf>a#a-mf930709-001-p4s4w9</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>ODA</t_lemma>
             <functor>APP</functor>
             <tfa>f</tfa>
             <deepord>10</deepord>
             <gram>
              <sempos>n.denot</sempos>
              <gender>fem</gender>
              <number>nr</number>
             </gram>
            </LM>
           </children>
          </LM>
          <LM id="t-mf930709-001-p4s4w13">
           <a>
            <lex.rf>a#a-mf930709-001-p4s4w13</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>hlasovat</t_lemma>
           <functor>RSTR</functor>
           <tfa>f</tfa>
           <deepord>12</deepord>
           <gram>
            <sempos>v</sempos>
            <verbmod>ind</verbmod>
            <deontmod>decl</deontmod>
            <tense>ant</tense>
            <aspect>proc</aspect>
            <resultative>res0</resultative>
            <dispmod>disp0</dispmod>
            <iterativeness>it0</iterativeness>
           </gram>
           <val_frame.rf>v#v-w1053f1</val_frame.rf>
           <children>
            <LM id="t-mf930709-001-p4s4w12">
             <a>
              <lex.rf>a#a-mf930709-001-p4s4w12</lex.rf>
              <aux.rf>a#a-mf930709-001-p4s4w11</aux.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>který</t_lemma>
             <functor>PAT</functor>
             <tfa>t</tfa>
             <deepord>11</deepord>
             <gram>
              <sempos>n.pron.indef</sempos>
              <gender>inher</gender>
              <number>inher</number>
              <indeftype>relat</indeftype>
              <person>inher</person>
             </gram>
             <coref_gram.rf>t-mf930709-001-p4s4w7</coref_gram.rf>
            </LM>
            <LM id="t-mf930709-001-p4s4w14">
             <a>
              <lex.rf>a#a-mf930709-001-p4s4w14</lex.rf>
             </a>
             <nodetype>atom</nodetype>
             <t_lemma>jen</t_lemma>
             <functor>RHEM</functor>
             <tfa>f</tfa>
             <deepord>13</deepord>
            </LM>
            <LM id="t-mf930709-001-p4s4w15">
             <a>
              <lex.rf>a#a-mf930709-001-p4s4w15</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>část</t_lemma>
             <functor>ACT</functor>
             <tfa>f</tfa>
             <deepord>14</deepord>
             <gram>
              <sempos>n.denot</sempos>
              <gender>fem</gender>
              <number>sg</number>
             </gram>
             <children>
              <LM id="t-mf930709-001-p4s4w16">
               <a>
                <lex.rf>a#a-mf930709-001-p4s4w16</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>poslanec</t_lemma>
               <functor>MAT</functor>
               <tfa>f</tfa>
               <deepord>15</deepord>
               <gram>
                <sempos>n.denot</sempos>
                <gender>anim</gender>
                <number>pl</number>
               </gram>
               <children>
                <LM id="t-mf930709-001-p4s4w18">
                 <a>
                  <lex.rf>a#a-mf930709-001-p4s4w18</lex.rf>
                 </a>
                 <nodetype>complex</nodetype>
                 <t_lemma>strana</t_lemma>
                 <functor>APP</functor>
                 <tfa>f</tfa>
                 <deepord>16</deepord>
                 <gram>
                  <sempos>n.denot</sempos>
                  <gender>fem</gender>
                  <number>pl</number>
                 </gram>
                 <children>
                  <LM id="t-mf930709-001-p4s4w17">
                   <a>
                    <lex.rf>a#a-mf930709-001-p4s4w17</lex.rf>
                   </a>
                   <nodetype>complex</nodetype>
                   <t_lemma>vládní</t_lemma>
                   <functor>RSTR</functor>
                   <tfa>f</tfa>
                   <deepord>17</deepord>
                   <gram>
                    <sempos>adj.denot</sempos>
                    <degcmp>pos</degcmp>
                    <negation>neg0</negation>
                   </gram>
                  </LM>
                 </children>
                </LM>
               </children>
              </LM>
             </children>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
 </trees>
</tdata>
